
This is a PLACEHOLDER for a CDDL definition derived from the YANG model.
SID experimental base 60100 is used.

dictionary keys are:
60100      ietf-cwt-voucher
60101      assertion
60102      created-on
60103      domain-cert-revocation-checks
60104      expires-on
60105      idevid-issuer
60106      last-renewal-date
60107      nonce
60108      pinned-domain-cert
60109      pinned-domain-subject-public-key-info
60110      prior-signed-voucher
60111      serial-number




